---
title: "Data Import"
output: github_document
---

This file is for doig data import

## Import 2 CSVs

```{r}
library(tidyverse)
library(readxl)
```

Import our first dataset. 

```{r}
litters_df =
  read_csv( #always use read_csv() rather than read.csv()
    file = "data/FAS_litters.csv", 
    na = c("", "NA", ".")
  ) 

# both NAs and dots used for missing values --> need to fix

# also want to clean up variable names: (makes col names snake case)
litters_df = janitor::clean_names(litters_df)
```

Import second dataset
```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv", 
    skip = 3,  
    na = c("", "NA", ".")
  )

pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or tail
```{r}
head(litters_df, 20)

tail(pups_df, 5)
```

Skimming??
```{r}
skimr::skim(pups_df)
```

## Oh excel...
Jenny Bryan made `readxl`` to solve our problems
```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

Look at the data!
```{r}
mlb_df
```

Load some LotR words.

Import FOTR.
```{r}
fotr_df = read_excel(
  "data/LotR_Words.xlsx",
  range = "B3:D6"
)

fotr_df
```

What about Two Towers?
```{r}
tt_df = read_excel(
  "data/LotR_Words.xlsx",
  range = "F3:H6"
)

tt_df
```

